version: '3.10.2'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: django-k9s:v1
    environment:
      - PORT=8020
    env_file:
      - web/.env
    ports:
      - "8001:8020"
    